query {
  home {
    id
    header {
      id
      title
      description
      image {
        id
        url
      }
    }
    shortBio {
      id
      title
      displayAsColumn
      listContents {
        id
        title
        text
      }
      isJustified
      isCentered
      medias {
        id
        name
        formats
        url
        mime
      }
    }
  }
}