query {
  home {
    id
    header {
      id
      title
      description
      image {
        id
        url
      }
    }
    shortBio {
      id
      title
      content
      image {
        id
        url
        formats
      }
      imagePosition
    }
  }
}