# Write your query or mutation here
query {
  bio {
    id
    metadata {
        title
      description
      keywords
    }
    photo {
      id
      url
      formats
    }
    resume {
      id
      title
      displayAsColumn
      listContents {
        id
        title
        text
      }
      isJustified
      isCentered
      medias {
        id
        name
        url
      }
    }
    activities {
      id
      title
      displayAsColumn
      
      listContents {
        id
        title
        text
      }
      isJustified
      isCentered
      medias {
        id
        name
        formats
        url
        mime
      }
    }
  }
}